spring:
  artemis:
    broker-url: tcp://localhost:61616
    mode: native
    user: artemis
    password: simetraehcapa
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  # overridden for illustrative purposes (default timeout is 30s)
  mvc:
    async:
      request-timeout: 40000
