version: "3.9"

services:
  amq:
    image: vromero/activemq-artemis:2.15.0-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - amq_data:/var/lib/artemis/data
      - amq_etc:/var/lib/artemis/etc
      - amq_etc-override:/var/lib/artemis/etc-override
      - amq_lock:/var/lib/artemis/lock
      - amq_tmp:/var/lib/artemis/tmp
  axonserver:
    image: axoniq/axonserver:4.5.12
    ports:
      - 8024:8024
      - 8124:8124
    # https://docs.axoniq.io/reference-guide/axon-server/installation/docker-k8s/axon-server-se
    volumes:
      - axon_eventdata:/eventdata
      - axon_data:/data
volumes:
  amq_data:
  amq_etc:
  amq_etc-override:
  amq_lock:
  amq_tmp:
  axon_eventdata:
  axon_data:
